"""empty message

Revision ID: 07050b9add23
Revises: f5542b750efe
Create Date: 2025-03-19 06:37:50.989884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07050b9add23'
down_revision = 'f5542b750efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('admin_email', sa.String(length=120), nullable=False),
    sa.Column('admin_password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_email'),
    sa.UniqueConstraint('admin_password')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
