"""empty message

Revision ID: e228ccc75275
Revises: d0fd19262535
Create Date: 2025-03-11 02:20:46.993829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e228ccc75275'
down_revision = 'd0fd19262535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_column('problem_types')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('problem_types', mysql.TEXT(), nullable=False))

    # ### end Alembic commands ###
